version: "3"

services:

  app:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    command: npm start
  